### ISSUE TITLE
Java | Webhooks - Fails to Get Notification Subscription

### ISSUE THREAD

**Issue by tarasklimenko** [attdevsupport/att-html5-sdk#116]
#### Description: 
When attempting to get notification subscription (details) in HTML5 Java Sample App, no details are shown. Empty response is returned. 

requested:
```
GET http://localhost:4567/att/notification/v1/subscriptions
```
returned:
```
{}
```

#### Expected: 
When calling to get notification subscription, all subscriptions should be listed

#### Actual:
subscription is not listed, "{}" empty response 

#### Repro:
1) Via HTML5 Java IAM Sample, Make channel & subscription
2) Make few sms/mms calls to make new notifications
3) Call to GET http://localhost:4567/att/notification/v1/subscriptions
4) Notice "{}" returned

**Comment by mattcobb** [comment]
This won't give you all the subscriptions.  Java server is storing each subscription in session data and different sessions can't access each other easily.  The platform does not support this either.  I suggested we do this earlier to help test, but turns out it is not possible.  You should only see the subscription for that service.

**Comment by tarasklimenko** [comment]
Confirmed not an issue. Closing.
